name: "wakatime-gist"
author: "abordage"
description: "Show your WakaTime statistics in a pinned gist for your GitHub profile"

inputs:
  INPUT_GH_TOKEN:
    description: 'GitHub token'
    required: true

  INPUT_WAKA_API_KEY:
    description: 'API key for your WakaTime account'
    required: true

  INPUT_IS_PROD:
    default: true

runs:
  using: "node16"
  main: "dist/index.js"

branding:
  icon: "paperclip"
  color: "blue"